# Pinned to the same signature database as xbcompat/tools/xbrun.py.
XBSYMBOLDATABASE_VERSION = 20eced544726f5558c5a408458f38a086cc4e543
XBSYMBOLDATABASE_SITE = $(call github,Cxbx-Reloaded,XbSymbolDatabase,$(XBSYMBOLDATABASE_VERSION))
XBSYMBOLDATABASE_LICENSE = MIT
XBSYMBOLDATABASE_LICENSE_FILES = LICENSE
XBSYMBOLDATABASE_SUPPORTS_IN_SOURCE_BUILD = NO
XBSYMBOLDATABASE_CONF_OPTS = -DXBSDB_BUILD_CLI=ON -DXBSDB_BUILD_UNITTEST=OFF \
	-DXBSDB_INSTALL_LIB=OFF -DXBSDB_INSTALL_CLI=OFF

define XBSYMBOLDATABASE_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/buildroot-build/projects/cli/XbSymbolDatabaseCLI \
		$(TARGET_DIR)/usr/bin/XbSymbolDatabaseCLI
endef

$(eval $(cmake-package))
