#!/usr/bin/env python3
"""Generate the xboxkrnl export table from the leak's ntoskrnl.src.

Every export is referenced as a weak symbol: when a C file in src/kernel
defines a function or variable with the export's name it lands in the table,
otherwise the loader patches in a stub that reports the missing ordinal.
"""
import re
import sys

src, out = sys.argv[1], sys.argv[2]
exports = []
for line in open(src, encoding="latin-1"):
    m = re.match(r"\s+(\w+)(?:\s*=\s*\w+)?\s+@(\d+)\s+NONAME(\s+CONSTANT)?", line)
    if m:
        exports.append((int(m.group(2)), m.group(1), bool(m.group(3))))
exports.sort()

with open(out, "w") as f:
    f.write("/* Generated by tools/gen_exports.py from private/ntos/init/ntoskrnl.src. */\n")
    f.write('#include <stddef.h>\n#include "exports.h"\n\n')
    for _, name, _ in exports:
        f.write(f"extern char {name} __attribute__((weak));\n")
    f.write("\nconst struct kexport kernel_exports[] = {\n")
    for ordinal, name, data in exports:
        f.write(f'    {{ {ordinal}, "{name}", &{name}, {int(data)} }},\n')
    f.write("    { 0, NULL, NULL, 0 },\n};\n")
