#!/usr/bin/env python3
"""Generate x86 ABI stubs from d3d8.c's authoritative HLE export table.
The native adapters decode arguments and return the exact stack cleanup.
"""
import re
import sys
from pathlib import Path
text = Path(sys.argv[1]).read_text()
marker = "const struct hle_func d3d8_funcs[] ="
if text.count(marker) != 1:
    raise SystemExit("cannot locate unique D3D export table")
table = re.sub(r"/\*.*?\*/", "", text.split(marker)[1], flags=re.S)
names = re.findall(r'F\(\s*("(?:[^"\\]|\\.)*")\s*,\s*\w+\s*\)', table)
if not names or len(names) != len(re.findall(r"\bF\s*\(", table)):
    raise SystemExit("unrecognized D3D export table entry")
print('/* Generated by tools/gen_renderer_stubs.py. */')
print('#include "xbcompat.h"')
print('#include "hle/hle.h"')
for i in range(len(names)):
    print(f'extern void xbr_stub_{i}(void);')
    print(f'__asm__(".text\\n.hidden xbr_stub_{i}\\n.type xbr_stub_{i},@function\\n'
          f'xbr_stub_{i}:\\npushl {chr(36)}{i}\\njmp xbr_entry\\n");')
print('const struct hle_func d3d8_funcs[] = {')
for i, name in enumerate(names):
    print(f'    {{ {name}, xbr_stub_{i} }},')
print('    {0, 0}\n};')
